### ISSUE TITLE
Typo in readme + odd option

### ISSUE THREAD

**Issue by dhritzkiv** [HenrikJoreteg/slugger#4]
It seems in the Readme, the second example is missing the `{decode: true}` option that you mention on the first line:

````javascript
// decodes URI components by default, if you don't want that pass {decode: true};
slugger('boo%20boo') // returns 'boo-boo';
// now with decode
slugger('boo%20boo') // returns boo20boo;
````

However, shouldn't the option to not decode URI Components be `{decode: false}` if you don't want to `decodeURIComponent`?

**Comment by fyockm** [comment]
Fixed by #5
